services:
 db:
   image: mysql:8.0
   container_name: ED_db
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=1234aa
     - MYSQL_DATABASE=masters_portal
   volumes:
     - 'db_data:/var/lib/mysql'
volumes:
  db_data: